### ISSUE TITLE
Question about memory usage

### ISSUE THREAD

**Issue by naveen17797** [internetarchive/heritrix3#462]
i have around 2-3 jobs running everyday, when the jobs run the heap usage increases, once the jobs finish the heap usage retains the increased value. i am using a fork of heritrix, so i wanted to understand if this is the default behaviour, should the memory be freed after the job is complete? or its the default behaviour to retain the memory usage ? I

![2022-02-07_17-49](https://user-images.githubusercontent.com/18109258/152786955-68e7520f-4004-4552-b7df-c38a422db994.png)

**Comment by anjackson** [comment]
This is the expected behaviour for any Java program, as the memory will only be freed when the garbage collection runs.  What should happen is that if you press the blue `run garbage collector` button, the heap should drop back down to close to the original value.  There are cases where not all memory can be freed, so it might not go the the exact same value, but it should be fairly close.

If you find this is not the case, feel free to reopen this issue.

**Comment by anjackson** [comment]
Heritrix has no in-built method for job scheduling at all. The number of jobs running and the resource usage is expected to be managed by the operator. Sorry for the late delivery of bad news!
