### ISSUE TITLE
Heritrix not ignoring robots.txt

### ISSUE THREAD

**Issue by Electrk** [internetarchive/heritrix3#479]
I am trying to crawl a website where I want Heritrix to ignore robots.txt and archive everything. However, despite the fact that I have `robotsPolicyName` set to `ignore`, it's still looking at robots.txt and not visiting certain pages:

![](https://i.imgur.com/J8v21Uq.png)

How do I fix this?

**Comment by ato** [comment]
`metadata.robotsPolicyName=ignore` should make Heritrix ignore the robots.txt rules, we use this option regularly. I don't think it prevents fetching robots.txt itself though. Pages which are not fetched due to robots.txt appear in crawl.log with status -9998. If the pages are not appearing at all in the log that would instead indicate a scoping or link extraction problem.

**Comment by Electrk** [comment]
Hmmm... okay
