### ISSUE TITLE
Error: Could not find or load main class org.archive.crawler.Heritrix Caused by: java.lang.ClassNotFoundException: org.archive.crawler.Heritrix

### ISSUE THREAD

**Issue by Moogamouth** [internetarchive/heritrix3#546]
I am getting an error upon running the command
`$HERITRIX_HOME/dist/src/main/bin/heritrix -a admin:admin`

It seems that lib is a non-existent directory:
```$HERITRIX_HOME/dist/src/main/bin/heritrix -a admin:admin
ls: cannot access '/home/moogamouth/heritrix3-3.4.0-20220727/lib/*.jar': No such file or directory
Sat Feb 11 10:44:47 PM EST 2023 Heritrix starting (pid 50275)
ERROR: JVM terminated without running Heritrix.
This could be due to invalid JAVA_OPTS or JMX_PORT, etc.
See heritrix_out.log for more details.
Here are its last three lines: 

file locks                          (-x) unlimited
Error: Could not find or load main class org.archive.crawler.Heritrix
Caused by: java.lang.ClassNotFoundException: org.archive.crawler.Heritrix```

**Comment by ato** [comment]
The [Heritrix distribution zip file](https://repo1.maven.org/maven2/org/archive/heritrix/heritrix/3.4.0-20220727/heritrix-3.4.0-20220727-dist.zip) unpacks to a directory named "heritrix-3.4.0-20220727" while your error message mentions "heritrix**3**-3.4.0-20220727". Perhaps this is a clue to what the problem is? I would double check that HERITRIX_HOME is set correctly and that Heritrix was installed from the correct zip file.
